use laboratorio;
-- CAMBIO MAYUS NOMBRE COMPAÑIA--
UPDATE CLIENTES_NEPTUNO
SET NOMBRECOMPANIA = UPPER(NOMBRECOMPANIA);
SELECT * FROM CLIENTES_NEPTUNO;
-- USA X ESTADOS UNIDOS -- 
SET SQL_SAFE_UPDATES = 0;
UPDATE CLIENTES_NEPTUNO
SET PAIS = 'USA' WHERE PAIS = 'ESTADOS UNIDOS';
SELECT * FROM CLIENTES_NEPTUNO;
-- 
ALTER TABLE EMPLEADOS ADD NOMBRE_EMPLEADO VARCHAR(30) AFTER IDEMPLEADO;
UPDATE EMPLEADOS
SET NOMBRE_EMPLEADO = CONCAT(APELLIDOS, ', ', NOMBRE);
ALTER TABLE EMPLEADOS DROP APELLIDOS, DROP NOMBRE;
SELECT * FROM EMPLEADOS;

--
ALTER TABLE CLIENTES ADD TIPO VARCHAR(3);
UPDATE CLIENTES SET TIPO = 'VIP' WHERE CUIT = 'MADRID';
SELECT * FROM CLIENTES;

ALTER TABLE CLIENTES MODIFY TELEFONO VARCHAR(20);
UPDATE CLIENTES
SET TELEFONO = CONCAT('+34-', TELEFONO) WHERE TELEFONO IS NOT NULL;
SELECT * FROM CLIENTES;





